# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1zF82kVWyf0Aj7GqhVCUT284F8fTiVo
"""

import numpy as np
import matplotlib.pyplot as plt

def L(S, o):
    # Sample implementation of L(S, o)
    return np.sin(S) * np.cos(o)

# Generate data for heatmap
S = np.linspace(0, 1, 100)
o = np.linspace(0, 1, 100)
S, o = np.meshgrid(S, o)
Z = L(S, o)

# Plot p2 (heatmap)
plt.subplot(2, 1, 1)
plt.imshow(Z, extent=(0, 1, 0, 1), origin='lower', cmap='jet')
plt.xlabel('S')
plt.ylabel('o')
plt.title("Bird's eye view")
plt.axvline(12, color='black')  # Add vertical line

# Plot p3 (curve)
plt.subplot(2, 1, 2)
plt.plot(o, L(25, o))
plt.xlabel('o')
plt.title('L(o|S=12)')

# Adjust spacing between subplots
plt.tight_layout()

# Save the figure
plt.savefig('python_fig.png')

# Display the figure
plt.show()