# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xc4loKkfODO7gVKwVyJLBY9WcJQEdJ2h
"""

import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Load the dataset (replace 'dataset.csv' with the actual path to your dataset file)
df = pd.read_csv('/content/pca-demo-food-country.csv')

# Exclude the first column from the dataset
data = df.iloc[:, 1:].values

# Perform PCA
pca = PCA(n_components=2, random_state=42)
new_data = pca.fit_transform(data)

# Calculate the explained variance ratio
explained_variance_ratio = pca.explained_variance_ratio_

# Calculate the cumulative explained variance
cumulative_variance = np.cumsum(explained_variance_ratio)

# Print the explained variance ratio and cumulative explained variance
print("Explained Variance Ratio:")
print(explained_variance_ratio)
print("\nCumulative Explained Variance:")
print(cumulative_variance)

# Plot the new data
plt.scatter(new_data[:, 0], new_data[:, 1])
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("Scatter Plot of PCA-transformed Data")
plt.show()